[tool.poetry]
name = "tankersdk-identity"
version = "1.3.4"
description = "Tanker identity library"
authors = ["Tanker team <tech@tanker.io>"]
homepage = "https://github.com/TankerHQ/identity-python"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.5"
PyNacl = "^1.3.0"

[tool.poetry.dev-dependencies]
black = { version = "19.10b0", python = '^3.6' }
codecov = "^2.0.15"
pytest = "4.6.6"
pytest-cov = "2.7.1"
mypy = "^0.770"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

